# Generated by Django 3.2.16 on 2023-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_meme',
            field=models.BooleanField(default=False),
        ),
    ]
