# Generated by Django 3.2.16 on 2023-05-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230503_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_meme',
        ),
    ]
