# Generated by Django 3.2.16 on 2023-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_meme',
            field=models.BooleanField(default=False),
        ),
    ]
