# Generated by Django 3.2.16 on 2023-05-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_otz1yg.jpg', upload_to='images/'),
        ),
    ]
