# Generated by Django 3.2.16 on 2023-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dxhzp2rnu/image/upload/v1683695518/media/images/default_profile_otz1yg.jpg', upload_to='images/'),
        ),
    ]
